// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentsService is the frontend-facing API and the owner of the background
 * plumbing that keeps the store fresh.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachImage stages one image for a known pane and returns the host path.
 * The caller is expected to send that path into the agent (SendText / prompt).
 */
export function AttachImage(paneID: string, declaredMIME: string, data: string | null): $CancellablePromise<string> {
    return $Call.ByID(3999166657, paneID, declaredMIME, data);
}

/**
 * AttachImageB64 is the Wails-friendly form: base64-encoded image bytes.
 */
export function AttachImageB64(paneID: string, mime: string, b64: string): $CancellablePromise<string> {
    return $Call.ByID(2107673867, paneID, mime, b64);
}

/**
 * Connection reports herdr connectivity.
 */
export function Connection(): $CancellablePromise<$models.Conn> {
    return $Call.ByID(1012542057);
}

/**
 * Counts returns a summary of the herd.
 */
export function Counts(): $CancellablePromise<$models.Counts> {
    return $Call.ByID(2920819413);
}

/**
 * Focus brings a pane to the foreground in herdr.
 */
export function Focus(paneID: string): $CancellablePromise<void> {
    return $Call.ByID(1388507619, paneID);
}

/**
 * Interrupt sends Ctrl+c to a pane.
 */
export function Interrupt(paneID: string): $CancellablePromise<void> {
    return $Call.ByID(1361927328, paneID);
}

/**
 * List returns the current agents, most urgent first.
 */
export function List(): $CancellablePromise<$models.Agent[] | null> {
    return $Call.ByID(1694561137);
}

/**
 * Read returns recent plain-text output for a pane.
 */
export function Read(paneID: string, lines: number): $CancellablePromise<string> {
    return $Call.ByID(1963257493, paneID, lines);
}

/**
 * ReadANSI is Read but preserves ANSI/SGR colour and style escapes instead
 * of stripping them, for a renderer that can display them. Both the web
 * dashboard and the desktop panel use it — the panel used plain Read until
 * its terminal was noticed to be monochrome next to the browser's.
 */
export function ReadANSI(paneID: string, lines: number): $CancellablePromise<string> {
    return $Call.ByID(3177936194, paneID, lines);
}

/**
 * RenamePane sets a pane's display name via herdr.
 */
export function RenamePane(paneID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3501485573, paneID, name);
}

/**
 * RenameTab sets a tab's display name via herdr.
 * 
 * Unlike pane writes there is no Guard.CheckPane-equivalent here: tabs are
 * not tracked as first-class entities in Store, only as a field on the panes
 * within them. The web layer authorises the request against an agent
 * occupying the tab before this is ever called (see
 * Server.authorizeControl), which is also what stands in for "does this tab
 * exist".
 */
export function RenameTab(tabID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(484518810, tabID, name);
}

/**
 * RenameWorkspace sets a workspace's display name via herdr. See RenameTab
 * for why there is no store-backed existence check here.
 */
export function RenameWorkspace(workspaceID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1179562728, workspaceID, name);
}

/**
 * Respond answers an agent's approval prompt with a canned reply.
 */
export function Respond(paneID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(789622870, paneID, text);
}

/**
 * SendKeys presses allowlisted keys in a pane.
 */
export function SendKeys(paneID: string, keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2484043855, paneID, keys);
}

/**
 * SendText writes arbitrary text and submits it, which is what a person typing
 * a reply expects. Higher trust than Respond: bounded by length only. Prefer
 * Respond where the answer is one of the canned options.
 * 
 * Routing:
 *   - Pane hosts a coding agent (omp/pi/claude/grok/…) → herdr agent.prompt.
 *     That path is harness-aware, so slash commands (/help, /status, …) work
 *     the same way they do when typed in the agent TUI.
 *   - Plain shell pane → SubmitText (send_text + Enter).
 */
export function SendText(paneID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(4058322216, paneID, text);
}

/**
 * Sessions enumerates every herdr session this machine knows about,
 * best-effort probed for reachability and pane/agent counts.
 */
export function Sessions(): $CancellablePromise<$models.SessionInfo[] | null> {
    return $Call.ByID(2577011260);
}

/**
 * SlashCommands returns typeahead hits for the composer when the user types
 * "/…" in a pane. paneID is the active pane: project skills are loaded from
 * that pane's known CWD only — never from a client-supplied path.
 * agent/query may still be passed for label matching; empty agent falls back
 * to the store projection for the pane.
 */
export function SlashCommands(paneID: string, agent: string, query: string): $CancellablePromise<$models.SlashCommand[] | null> {
    return $Call.ByID(1176936456, paneID, agent, query);
}

/**
 * StreamOutput streams a pane's live output until ctx is cancelled, calling
 * onText with the latest rendering on every matching change.
 * 
 * ctx is the CALLER's context, not s.ctx: unlike the service's own
 * background streams, which live for the whole app, a pane subscription
 * must end the moment its one subscriber — an HTTP request, say — goes
 * away, not when the app itself shuts down.
 */
export function StreamOutput(paneID: string, lines: number, onText: any): $CancellablePromise<void> {
    return $Call.ByID(1824822516, paneID, lines, onText);
}

/**
 * StreamOutputANSI is StreamOutput but preserves ANSI/SGR colour and style
 * escapes instead of stripping them. See ReadANSI.
 */
export function StreamOutputANSI(paneID: string, lines: number, onText: any): $CancellablePromise<void> {
    return $Call.ByID(78234507, paneID, lines, onText);
}

/**
 * SwitchSession repoints the service at a different herdr session's socket.
 * 
 * The previous session's background goroutines are cancelled before the new
 * generation's are started, so the store is never fed events from two
 * sessions at once. id is resolved through Sessions rather than trusted as a
 * path, so a caller can never point the server at an arbitrary socket.
 */
export function SwitchSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(769073955, id);
}
