// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as herdr$0 from "../herdr/models.js";

/**
 * Agent is the frontend-facing view of an agent pane.
 * 
 * This is deliberately a projection rather than herdr.PaneInfo: it carries
 * derived fields the UI needs and shields the frontend from wire churn when
 * herdr's schema moves.
 */
export interface Agent {
    "paneId": string;
    "agent": string;
    "status": herdr$0.AgentStatus;
    "project": string;
    "cwd": string;
    "workspaceId": string;
    "tabId": string;
    "focused": boolean;
    "needsAttention": boolean;
}

/**
 * Conn describes connectivity to the herdr server.
 */
export interface Conn {
    "connected": boolean;
    "version": string;
    "protocol": number;
    "socket": string;
    "error"?: string;
}

/**
 * Counts summarises the herd for the tray label.
 */
export interface Counts {
    "total": number;
    "blocked": number;
    "working": number;
}

/**
 * SessionInfo describes one herdr session this machine can reach: the
 * default socket herdr uses when none is named, plus every named session
 * under ~/.config/herdr/sessions/*. ListSessions is the only thing that
 * constructs these, so a caller of SwitchSession can never point the server
 * at a socket outside this list.
 */
export interface SessionInfo {
    "id": string;
    "name": string;
    "socket": string;
    "panes": number;
    "agents": number;
    "reachable": boolean;
    "current": boolean;
}

/**
 * SlashCommand is one entry in the composer typeahead.
 * 
 * Name is what the user types after '/' (no leading slash). Value is the full
 * text inserted into the composer (usually "/"+Name, sometimes "skill:Name "
 * for omp skill dispatch).
 */
export interface SlashCommand {
    "name": string;
    "value": string;
    "description"?: string;

    /**
     * builtin | skill | plugin
     */
    "source"?: string;
}
