// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessOrigin is a base URL the phone can open for pairing/login.
 */
export class AccessOrigin {
    /**
     * Kind is "local", "lan", "tailscale", or "public".
     */
    "kind": string;

    /**
     * Label is short UI copy, e.g. "This Mac" / "Wi‑Fi".
     */
    "label": string;

    /**
     * URL is the origin only (scheme://host:port), no path.
     */
    "url": string;

    /**
     * Hint is one-line guidance under the chip.
     */
    "hint": string;

    /** Creates a new AccessOrigin instance. */
    constructor($$source: Partial<AccessOrigin> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("hint" in $$source)) {
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessOrigin instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessOrigin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessOrigin($$parsedSource as Partial<AccessOrigin>);
    }
}

/**
 * Device is a paired browser/phone that redeemed a QR (or future OAuth link).
 * 
 * Devices are the durable identity unit for the public-release ladder: a
 * stolen phone session is one row to revoke, not the master password.
 */
export class Device {
    "id": string;
    "name": string;
    "provider": string;
    "roles": string[];
    "createdAt": string;
    "lastSeen": string;
    "revokedAt"?: string | null;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("roles" in $$source)) {
            this["roles"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField3_0($$parsedSource["roles"]);
        }
        return new Device($$parsedSource as Partial<Device>);
    }
}

/**
 * GitHubSettings is the editable, secret-in write shape from the UI.
 */
export class GitHubSettings {
    "clientID": string;

    /**
     * empty ⇒ keep the stored secret
     */
    "clientSecret": string;
    "allow": string[];
    "org": string;
    "team": string;
    "label": string;

    /** Creates a new GitHubSettings instance. */
    constructor($$source: Partial<GitHubSettings> = {}) {
        if (!("clientID" in $$source)) {
            this["clientID"] = "";
        }
        if (!("clientSecret" in $$source)) {
            this["clientSecret"] = "";
        }
        if (!("allow" in $$source)) {
            this["allow"] = [];
        }
        if (!("org" in $$source)) {
            this["org"] = "";
        }
        if (!("team" in $$source)) {
            this["team"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubSettings {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allow" in $$parsedSource) {
            $$parsedSource["allow"] = $$createField2_0($$parsedSource["allow"]);
        }
        return new GitHubSettings($$parsedSource as Partial<GitHubSettings>);
    }
}

/**
 * OAuthProviderStatus is the non-secret view of one provider for the UI. The
 * client secret is NEVER included — only whether one is stored.
 */
export class OAuthProviderStatus {
    /**
     * live-enabled ⇒ a button shows
     */
    "configured": boolean;
    "locked": boolean;
    "source": string;
    "clientID": string;
    "hasSecret": boolean;
    "allow"?: string[];
    "org"?: string;
    "team"?: string;
    "issuer"?: string;
    "allowRole"?: string;
    "label": string;
    "redirectURL": string;

    /** Creates a new OAuthProviderStatus instance. */
    constructor($$source: Partial<OAuthProviderStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("clientID" in $$source)) {
            this["clientID"] = "";
        }
        if (!("hasSecret" in $$source)) {
            this["hasSecret"] = false;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("redirectURL" in $$source)) {
            this["redirectURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthProviderStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OAuthProviderStatus {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allow" in $$parsedSource) {
            $$parsedSource["allow"] = $$createField4_0($$parsedSource["allow"]);
        }
        return new OAuthProviderStatus($$parsedSource as Partial<OAuthProviderStatus>);
    }
}

/**
 * OAuthStatus is the whole Settings view: both providers plus whether a public
 * URL exists at all (without one, no provider can be enabled).
 */
export class OAuthStatus {
    "publicUrlSet": boolean;
    "github": OAuthProviderStatus;
    "oidc": OAuthProviderStatus;

    /** Creates a new OAuthStatus instance. */
    constructor($$source: Partial<OAuthStatus> = {}) {
        if (!("publicUrlSet" in $$source)) {
            this["publicUrlSet"] = false;
        }
        if (!("github" in $$source)) {
            this["github"] = (new OAuthProviderStatus());
        }
        if (!("oidc" in $$source)) {
            this["oidc"] = (new OAuthProviderStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): OAuthStatus {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("github" in $$parsedSource) {
            $$parsedSource["github"] = $$createField1_0($$parsedSource["github"]);
        }
        if ("oidc" in $$parsedSource) {
            $$parsedSource["oidc"] = $$createField2_0($$parsedSource["oidc"]);
        }
        return new OAuthStatus($$parsedSource as Partial<OAuthStatus>);
    }
}

/**
 * OIDCSettings is the editable, secret-in write shape from the UI.
 */
export class OIDCSettings {
    "clientID": string;

    /**
     * empty ⇒ keep the stored secret
     */
    "clientSecret": string;
    "issuer": string;
    "allowRole": string;
    "label": string;

    /** Creates a new OIDCSettings instance. */
    constructor($$source: Partial<OIDCSettings> = {}) {
        if (!("clientID" in $$source)) {
            this["clientID"] = "";
        }
        if (!("clientSecret" in $$source)) {
            this["clientSecret"] = "";
        }
        if (!("issuer" in $$source)) {
            this["issuer"] = "";
        }
        if (!("allowRole" in $$source)) {
            this["allowRole"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OIDCSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): OIDCSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OIDCSettings($$parsedSource as Partial<OIDCSettings>);
    }
}

/**
 * PairingTicket is what the desktop Settings sheet renders.
 */
export class PairingTicket {
    /**
     * URL is the full link encoded into the QR (…/login?token=…).
     */
    "url": string;

    /**
     * Token is the raw secret, shown as a copy-paste fallback for phones
     * that cannot scan.
     */
    "token": string;

    /**
     * QRPNG is a data-URL (image/png;base64,…) of the QR code.
     */
    "qrPng": string;

    /**
     * ExpiresAt is a unix timestamp when the token stops working.
     */
    "expiresAt": number;

    /** Creates a new PairingTicket instance. */
    constructor($$source: Partial<PairingTicket> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("qrPng" in $$source)) {
            this["qrPng"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingTicket instance from a string or object.
     */
    static createFrom($$source: any = {}): PairingTicket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingTicket($$parsedSource as Partial<PairingTicket>);
    }
}

/**
 * Server is the read-only HTTP dashboard.
 */
export class Server {

    /** Creates a new Server instance. */
    constructor($$source: Partial<Server> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     */
    static createFrom($$source: any = {}): Server {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server($$parsedSource as Partial<Server>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = OAuthProviderStatus.createFrom;
