// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccessOrigin is a base URL the phone can open for pairing/login.
 */
export interface AccessOrigin {
    /**
     * Kind is "local", "lan", "tailscale", or "public".
     */
    "kind": string;

    /**
     * Label is short UI copy, e.g. "This Mac" / "Wi‑Fi".
     */
    "label": string;

    /**
     * URL is the origin only (scheme://host:port), no path.
     */
    "url": string;

    /**
     * Hint is one-line guidance under the chip.
     */
    "hint": string;
}

/**
 * Device is a paired browser/phone that redeemed a QR (or future OAuth link).
 * 
 * Devices are the durable identity unit for the public-release ladder: a
 * stolen phone session is one row to revoke, not the master password.
 */
export interface Device {
    "id": string;
    "name": string;
    "provider": string;
    "roles": string[] | null;
    "createdAt": string;
    "lastSeen": string;
    "revokedAt"?: string | null;
}

/**
 * PairingTicket is what the desktop Settings sheet renders.
 */
export interface PairingTicket {
    /**
     * URL is the full link encoded into the QR (…/login?token=…).
     */
    "url": string;

    /**
     * Token is the raw secret, shown as a copy-paste fallback for phones
     * that cannot scan.
     */
    "token": string;

    /**
     * QRPNG is a data-URL (image/png;base64,…) of the QR code.
     */
    "qrPng": string;

    /**
     * ExpiresAt is a unix timestamp when the token stops working.
     */
    "expiresAt": number;
}

/**
 * Server is the read-only HTTP dashboard.
 */
export interface Server {
}
