// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessOrigin is a base URL the phone can open for pairing/login.
 */
export class AccessOrigin {
    /**
     * Kind is "local", "lan", or "public".
     */
    "kind": string;

    /**
     * Label is short UI copy, e.g. "This Mac" / "Wi‑Fi".
     */
    "label": string;

    /**
     * URL is the origin only (scheme://host:port), no path.
     */
    "url": string;

    /**
     * Hint is one-line guidance under the chip.
     */
    "hint": string;

    /** Creates a new AccessOrigin instance. */
    constructor($$source: Partial<AccessOrigin> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("hint" in $$source)) {
            this["hint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessOrigin instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessOrigin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessOrigin($$parsedSource as Partial<AccessOrigin>);
    }
}

/**
 * Device is a paired browser/phone that redeemed a QR (or future OAuth link).
 * 
 * Devices are the durable identity unit for the public-release ladder: a
 * stolen phone session is one row to revoke, not the master password.
 */
export class Device {
    "id": string;
    "name": string;
    "provider": string;
    "roles": string[];
    "createdAt": string;
    "lastSeen": string;
    "revokedAt"?: string | null;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("roles" in $$source)) {
            this["roles"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roles" in $$parsedSource) {
            $$parsedSource["roles"] = $$createField3_0($$parsedSource["roles"]);
        }
        return new Device($$parsedSource as Partial<Device>);
    }
}

/**
 * PairingTicket is what the desktop Settings sheet renders.
 */
export class PairingTicket {
    /**
     * URL is the full link encoded into the QR (…/login?token=…).
     */
    "url": string;

    /**
     * Token is the raw secret, shown as a copy-paste fallback for phones
     * that cannot scan.
     */
    "token": string;

    /**
     * QRPNG is a data-URL (image/png;base64,…) of the QR code.
     */
    "qrPng": string;

    /**
     * ExpiresAt is a unix timestamp when the token stops working.
     */
    "expiresAt": number;

    /** Creates a new PairingTicket instance. */
    constructor($$source: Partial<PairingTicket> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("qrPng" in $$source)) {
            this["qrPng"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingTicket instance from a string or object.
     */
    static createFrom($$source: any = {}): PairingTicket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingTicket($$parsedSource as Partial<PairingTicket>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
