// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PairingTicket is what the desktop Settings sheet renders.
 */
export interface PairingTicket {
    /**
     * URL is the full link encoded into the QR (…/login?token=…).
     */
    "url": string;

    /**
     * Token is the raw secret, shown as a copy-paste fallback for phones
     * that cannot scan.
     */
    "token": string;

    /**
     * QRPNG is a data-URL (image/png;base64,…) of the QR code.
     */
    "qrPng": string;

    /**
     * ExpiresAt is a unix timestamp when the token stops working.
     */
    "expiresAt": number;
}
