// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInfo is what Settings renders.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "newer": boolean;
    "releaseUrl": string;
    "body": string;
    "published": string;
    "checkedAt": number;
}
