// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the Wails-bound surface for desktop-only preferences:
 * launch-at-login, GitHub updates, and phone pairing QR tickets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as web$0 from "../web/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccessOrigins returns localhost + LAN (and never invents a Cloudflare URL).
 * The Settings sheet uses these as one-tap QR bases before any tunnel setup.
 */
export function AccessOrigins(): $CancellablePromise<web$0.AccessOrigin[]> {
    return $Call.ByID(2231323965).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckUpdate looks up the latest GitHub release.
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(544266481).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DefaultPairBase is the best LAN/local origin for a first QR.
 */
export function DefaultPairBase(): $CancellablePromise<string> {
    return $Call.ByID(3168493468);
}

/**
 * FirstRunPending reports whether the first-run pairing splash should show.
 */
export function FirstRunPending(): $CancellablePromise<boolean> {
    return $Call.ByID(2333329006);
}

/**
 * LaunchAtLogin reports whether the app opens at login.
 */
export function LaunchAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(4163321067);
}

/**
 * ListDevices returns paired phones (including revoked).
 */
export function ListDevices(): $CancellablePromise<web$0.Device[]> {
    return $Call.ByID(3218586955).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * MarkFirstRunDone suppresses the first-run pairing splash on later launches.
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(1665771882);
}

/**
 * MintPairing returns a short-lived QR ticket for phone login.
 */
export function MintPairing(): $CancellablePromise<web$0.PairingTicket> {
    return $Call.ByID(62924868).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OptionalPasswordEnabled reports whether a user-set phone password exists.
 */
export function OptionalPasswordEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3872930110);
}

/**
 * PasswordLoginEnabled reports whether HTTP username/password sign-in is on.
 */
export function PasswordLoginEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(723565347);
}

/**
 * RevokeAllDevices panic-revokes every paired phone session grant.
 */
export function RevokeAllDevices(): $CancellablePromise<number> {
    return $Call.ByID(3398594536);
}

/**
 * RevokeDevice marks one paired device revoked.
 */
export function RevokeDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(2930031968, id);
}

/**
 * SetLaunchAtLogin enables or disables open-at-login.
 */
export function SetLaunchAtLogin(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(768195563, on);
}

/**
 * SetOptionalPassword enables username/password phone login without QR.
 */
export function SetOptionalPassword(user: string, pass: string): $CancellablePromise<void> {
    return $Call.ByID(1017037253, user, pass);
}

/**
 * SetPairingBaseURL sets the public origin encoded into QR links
 * (e.g. https://herdr-tunnel.0dl.me).
 */
export function SetPairingBaseURL(base: string): $CancellablePromise<void> {
    return $Call.ByID(224920250, base);
}

/**
 * SetPasswordLoginEnabled turns HTTP user/pass sign-in on or off.
 * QR pairing is unaffected. Re-enable anytime from this desktop Settings UI.
 */
export function SetPasswordLoginEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1377255459, on);
}

// Private type creation functions
const $$createType0 = web$0.AccessOrigin.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.UpdateInfo.createFrom;
const $$createType3 = web$0.Device.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = web$0.PairingTicket.createFrom;
