// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the Wails-bound surface for desktop-only preferences:
 * launch-at-login, GitHub updates, and phone pairing QR tickets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as web$0 from "../web/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate looks up the latest GitHub release.
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(544266481);
}

/**
 * LaunchAtLogin reports whether the app opens at login.
 */
export function LaunchAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(4163321067);
}

/**
 * MintPairing returns a short-lived QR ticket for phone login.
 */
export function MintPairing(): $CancellablePromise<web$0.PairingTicket> {
    return $Call.ByID(62924868);
}

/**
 * SetLaunchAtLogin enables or disables open-at-login.
 */
export function SetLaunchAtLogin(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(768195563, on);
}

/**
 * SetPairingBaseURL sets the public origin encoded into QR links
 * (e.g. https://herdr-tunnel.0dl.me).
 */
export function SetPairingBaseURL(base: string): $CancellablePromise<void> {
    return $Call.ByID(224920250, base);
}

/**
 * ListDevices returns paired phones (including revoked).
 */
export function ListDevices(): $CancellablePromise<web$0.Device[]> {
    return $Call.ByID(3218586955);
}

/**
 * RevokeDevice marks one paired device revoked.
 */
export function RevokeDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(2930031968, id);
}

/**
 * RevokeAllDevices panic-revokes every paired phone session grant.
 */
export function RevokeAllDevices(): $CancellablePromise<number> {
    return $Call.ByID(3398594536);
}

/**
 * FirstRunPending reports whether the first-run pairing splash should show.
 */
export function FirstRunPending(): $CancellablePromise<boolean> {
    return $Call.ByID(2333329006);
}

/**
 * MarkFirstRunDone suppresses the first-run pairing splash on later launches.
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(1665771882);
}

/**
 * SetOptionalPassword enables username/password phone login without QR.
 */
export function SetOptionalPassword(user: string, pass: string): $CancellablePromise<void> {
    return $Call.ByID(1017037253, user, pass);
}

/**
 * OptionalPasswordEnabled reports whether a user-set phone password exists.
 */
export function OptionalPasswordEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3872930110);
}
