// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentsService is the frontend-facing API and the owner of the background
 * plumbing that keeps the store fresh.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connection reports herdr connectivity.
 */
export function Connection(): $CancellablePromise<$models.Conn> {
    return $Call.ByID(2291788203);
}

/**
 * Counts returns a summary of the herd.
 */
export function Counts(): $CancellablePromise<$models.Counts> {
    return $Call.ByID(3973762459);
}

/**
 * Focus brings a pane to the foreground in herdr.
 */
export function Focus(paneID: string): $CancellablePromise<void> {
    return $Call.ByID(2403718717, paneID);
}

/**
 * Interrupt sends Ctrl+c to a pane.
 */
export function Interrupt(paneID: string): $CancellablePromise<void> {
    return $Call.ByID(1096132326, paneID);
}

/**
 * List returns the current agents, most urgent first.
 */
export function List(): $CancellablePromise<$models.Agent[] | null> {
    return $Call.ByID(2878599779);
}

/**
 * Read returns recent plain-text output for a pane.
 */
export function Read(paneID: string, lines: number): $CancellablePromise<string> {
    return $Call.ByID(3652161007, paneID, lines);
}

/**
 * Respond answers an agent's approval prompt with a canned reply.
 */
export function Respond(paneID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(212324936, paneID, text);
}

/**
 * SendKeys presses allowlisted keys in a pane.
 */
export function SendKeys(paneID: string, keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2624467717, paneID, keys);
}

/**
 * SendText writes arbitrary text. Higher trust than Respond: bounded by length
 * only. Prefer Respond where the answer is one of the canned options.
 */
export function SendText(paneID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1262299878, paneID, text);
}
