// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as herdr$0 from "../herdr/models.js";

/**
 * Agent is the frontend-facing view of an agent pane.
 * 
 * This is deliberately a projection rather than herdr.PaneInfo: it carries
 * derived fields the UI needs and shields the frontend from wire churn when
 * herdr's schema moves.
 */
export interface Agent {
    "paneId": string;
    "agent": string;
    "status": herdr$0.AgentStatus;
    "project": string;
    "cwd": string;
    "workspaceId": string;
    "tabId": string;
    "focused": boolean;
    "needsAttention": boolean;
}

/**
 * Conn describes connectivity to the herdr server.
 */
export interface Conn {
    "connected": boolean;
    "version": string;
    "protocol": number;
    "socket": string;
    "error"?: string;
}

/**
 * Counts summarises the herd for the tray label.
 */
export interface Counts {
    "total": number;
    "blocked": number;
    "working": number;
}
