// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as herdr$0 from "../herdr/models.js";

/**
 * Agent is the frontend-facing view of an agent pane.
 * 
 * This is deliberately a projection rather than herdr.PaneInfo: it carries
 * derived fields the UI needs and shields the frontend from wire churn when
 * herdr's schema moves.
 */
export class Agent {
    "paneId": string;
    "agent": string;
    "status": herdr$0.AgentStatus;
    "project": string;
    "cwd": string;
    "workspaceId": string;
    "tabId": string;
    "focused": boolean;
    "needsAttention": boolean;

    /** Creates a new Agent instance. */
    constructor($$source: Partial<Agent> = {}) {
        if (!("paneId" in $$source)) {
            this["paneId"] = "";
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = herdr$0.AgentStatus.$zero;
        }
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("tabId" in $$source)) {
            this["tabId"] = "";
        }
        if (!("focused" in $$source)) {
            this["focused"] = false;
        }
        if (!("needsAttention" in $$source)) {
            this["needsAttention"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Agent instance from a string or object.
     */
    static createFrom($$source: any = {}): Agent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Agent($$parsedSource as Partial<Agent>);
    }
}

/**
 * Conn describes connectivity to the herdr server.
 */
export class Conn {
    "connected": boolean;
    "version": string;
    "protocol": number;
    "socket": string;
    "error"?: string;

    /** Creates a new Conn instance. */
    constructor($$source: Partial<Conn> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = 0;
        }
        if (!("socket" in $$source)) {
            this["socket"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Conn instance from a string or object.
     */
    static createFrom($$source: any = {}): Conn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Conn($$parsedSource as Partial<Conn>);
    }
}

/**
 * Counts summarises the herd for the tray label.
 */
export class Counts {
    "total": number;
    "blocked": number;
    "working": number;

    /** Creates a new Counts instance. */
    constructor($$source: Partial<Counts> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = 0;
        }
        if (!("working" in $$source)) {
            this["working"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Counts instance from a string or object.
     */
    static createFrom($$source: any = {}): Counts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Counts($$parsedSource as Partial<Counts>);
    }
}

/**
 * SessionInfo describes one herdr session this machine can reach: the
 * default socket herdr uses when none is named, plus every named session
 * under ~/.config/herdr/sessions/*. ListSessions is the only thing that
 * constructs these, so a caller of SwitchSession can never point the server
 * at a socket outside this list.
 */
export class SessionInfo {
    "id": string;
    "name": string;
    "socket": string;
    "panes": number;
    "agents": number;
    "reachable": boolean;
    "current": boolean;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("socket" in $$source)) {
            this["socket"] = "";
        }
        if (!("panes" in $$source)) {
            this["panes"] = 0;
        }
        if (!("agents" in $$source)) {
            this["agents"] = 0;
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("current" in $$source)) {
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

/**
 * SlashCommand is one entry in the composer typeahead.
 * 
 * Name is what the user types after '/' (no leading slash). Value is the full
 * text inserted into the composer (usually "/"+Name, sometimes "skill:Name "
 * for omp skill dispatch).
 */
export class SlashCommand {
    "name": string;
    "value": string;
    "description"?: string;

    /**
     * builtin | skill | plugin
     */
    "source"?: string;

    /** Creates a new SlashCommand instance. */
    constructor($$source: Partial<SlashCommand> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlashCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): SlashCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlashCommand($$parsedSource as Partial<SlashCommand>);
    }
}
