// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentStatus is the OBSERVED lifecycle state of an agent, as reported by the
 * server on pane.agent_status_changed and in PaneInfo.
 */
export enum AgentStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusWorking = "working",
    StatusBlocked = "blocked",
    StatusDone = "done",
    StatusUnknown = "unknown",
};
