// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigInfo is the Settings view of config.yml: where it is and whether it
 * exists yet. The frontend uses this to label the "Open config file" button.
 */
export interface ConfigInfo {
    "path": string;
    "exists": boolean;
}

/**
 * InstallResult is returned after DownloadAndInstall stages the update (before Restart).
 */
export interface InstallResult {
    "version": string;
    "message": string;
}

/**
 * UpdateInfo is what Settings renders.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "newer": boolean;
    "releaseUrl": string;

    /**
     * AssetName is the zip we would install (empty if none / wrong platform).
     */
    "assetName": string;

    /**
     * CanInstall is true when Framework is wired, a zip asset exists, and Newer.
     */
    "canInstall": boolean;
    "body": string;
    "published": string;
    "checkedAt": number;
}
