// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallResult is returned after DownloadAndInstall stages the update (before Restart).
 */
export class InstallResult {
    "version": string;
    "message": string;

    /** Creates a new InstallResult instance. */
    constructor($$source: Partial<InstallResult> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallResult($$parsedSource as Partial<InstallResult>);
    }
}

/**
 * UpdateInfo is what Settings renders.
 */
export class UpdateInfo {
    "current": string;
    "latest": string;
    "newer": boolean;
    "releaseUrl": string;

    /**
     * AssetName is the zip we would install (empty if none / wrong platform).
     */
    "assetName": string;

    /**
     * CanInstall is true when Framework is wired, a zip asset exists, and Newer.
     */
    "canInstall": boolean;
    "body": string;
    "published": string;
    "checkedAt": number;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("newer" in $$source)) {
            this["newer"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("canInstall" in $$source)) {
            this["canInstall"] = false;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("published" in $$source)) {
            this["published"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
