// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings is the Wails-bound surface for desktop-only preferences:
 * launch-at-login, GitHub updates, and phone pairing QR tickets.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as web$0 from "../web/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccessOrigins returns localhost + LAN (and never invents a Cloudflare URL).
 * The Settings sheet uses these as one-tap QR bases before any tunnel setup.
 */
export function AccessOrigins(): $CancellablePromise<web$0.AccessOrigin[]> {
    return $Call.ByID(3263902163).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AllowWritesEnabled reports whether phone/web may write to panes.
 */
export function AllowWritesEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(634830236);
}

/**
 * CheckUpdate looks up the latest GitHub release (read-only; does not download).
 */
export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3345746207).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConfigFileInfo reports the effective config path and whether it exists.
 */
export function ConfigFileInfo(): $CancellablePromise<$models.ConfigInfo> {
    return $Call.ByID(3538901526);
}

/**
 * OpenConfigFile opens config.yml in the OS default editor, creating it from a
 * fully-commented starter template first if it does not exist. Returns the
 * path opened.
 */
export function OpenConfigFile(): $CancellablePromise<string> {
    return $Call.ByID(2669502342);
}

/**
 * ClearOAuth removes a provider's stored config ("github" or "oidc").
 */
export function ClearOAuth(provider: string): $CancellablePromise<void> {
    return $Call.ByID(826742742, provider);
}

/**
 * DefaultPairBase is the best LAN/local origin for a first QR.
 */
export function DefaultPairBase(): $CancellablePromise<string> {
    return $Call.ByID(682371734);
}

/**
 * FirstRunPending reports whether the first-run pairing splash should show.
 */
export function FirstRunPending(): $CancellablePromise<boolean> {
    return $Call.ByID(1017264072);
}

/**
 * InstallUpdate downloads the latest macOS .app zip via Wails updater, verifies
 * SHA256SUMS, swaps the bundle, and relaunches. Call only after CheckUpdate
 * reported canInstall (or it re-checks). Blocks until staged; process then quits.
 */
export function InstallUpdate(): $CancellablePromise<$models.InstallResult> {
    return $Call.ByID(1410411228).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * LaunchAtLogin reports whether the app opens at login.
 */
export function LaunchAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(3253433921);
}

/**
 * ListDevices returns paired phones (including revoked).
 */
export function ListDevices(): $CancellablePromise<web$0.Device[]> {
    return $Call.ByID(2060505397).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * MarkFirstRunDone suppresses the first-run pairing splash on later launches.
 */
export function MarkFirstRunDone(): $CancellablePromise<void> {
    return $Call.ByID(2793653572);
}

/**
 * MintPairing returns a short-lived QR ticket for phone login.
 */
export function MintPairing(): $CancellablePromise<web$0.PairingTicket> {
    return $Call.ByID(4038686222).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * OAuthConfig returns the secret-free sign-in settings view for the Settings
 * sheet. Empty when the web server is not wired.
 */
export function OAuthConfig(): $CancellablePromise<web$0.OAuthStatus> {
    return $Call.ByID(2566841191).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * OptionalPasswordEnabled reports whether a user-set phone password exists.
 */
export function OptionalPasswordEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2544313696);
}

/**
 * PasswordLoginEnabled reports whether HTTP username/password sign-in is on.
 */
export function PasswordLoginEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3476260345);
}

/**
 * RevokeAllDevices panic-revokes every paired phone session grant.
 */
export function RevokeAllDevices(): $CancellablePromise<number> {
    return $Call.ByID(359353362);
}

/**
 * RevokeDevice marks one paired device revoked.
 */
export function RevokeDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(1098761902, id);
}

/**
 * SessionSwitchEnabled reports whether phone/web may switch herdr sessions.
 */
export function SessionSwitchEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2060384351);
}

/**
 * SetAllowWritesEnabled turns phone pane writes on or off.
 * Persists to disk and updates the live gate immediately.
 */
export function SetAllowWritesEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(657839220, on);
}

/**
 * SetLaunchAtLogin enables or disables open-at-login.
 */
export function SetLaunchAtLogin(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1033293945, on);
}

/**
 * SetOAuthGitHub applies and persists a GitHub sign-in edit, live.
 */
export function SetOAuthGitHub($in: web$0.GitHubSettings): $CancellablePromise<void> {
    return $Call.ByID(679993978, $in);
}

/**
 * SetOAuthOIDC applies and persists a Keycloak/OIDC sign-in edit, live.
 */
export function SetOAuthOIDC($in: web$0.OIDCSettings): $CancellablePromise<void> {
    return $Call.ByID(1037908360, $in);
}

/**
 * SetOptionalPassword enables username/password phone login without QR.
 */
export function SetOptionalPassword(user: string, pass: string): $CancellablePromise<void> {
    return $Call.ByID(400382803, user, pass);
}

/**
 * SetPairingBaseURL sets the public origin encoded into QR links
 * (e.g. https://merino.example).
 */
export function SetPairingBaseURL(base: string): $CancellablePromise<void> {
    return $Call.ByID(2392527176, base);
}

/**
 * SetPasswordLoginEnabled turns HTTP user/pass sign-in on or off.
 * QR pairing is unaffected. Re-enable anytime from this desktop Settings UI.
 */
export function SetPasswordLoginEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(4138468289, on);
}

/**
 * SetSessionSwitchEnabled turns phone session switching on or off.
 * Persists to disk and updates the live gate immediately.
 */
export function SetSessionSwitchEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(983522247, on);
}

/**
 * SetWebServer wires the live web server for runtime Settings toggles.
 */
export function SetWebServer(srv: web$0.Server | null): $CancellablePromise<void> {
    return $Call.ByID(2770529491, srv);
}

// Private type creation functions
const $$createType0 = web$0.AccessOrigin.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.UpdateInfo.createFrom;
const $$createType3 = $models.InstallResult.createFrom;
const $$createType4 = web$0.Device.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = web$0.PairingTicket.createFrom;
const $$createType7 = web$0.OAuthStatus.createFrom;
